# Generated by Django 5.0.2 on 2024-03-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0003_alter_participation_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=40)),
                ('logo', models.ImageField(upload_to='logo')),
                ('description', models.TextField()),
            ],
        ),
    ]
